version: "2.2"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sentimantic
      POSTGRES_USER: sentimantic
      PGDATA: /var/lib/postgresql/data/sentimantic
    ports:
      - 54320:5432
    volumes:
      - ./.database:/var/lib/postgresql/data/sentimantic
  lookup:
    image: dbpedia/lookup
    command: java -jar /opt/lookup/dbpedia-lookup-3.1-jar-with-dependencies.jar /opt/lookup/2015-10/
    restart: always
    scale: 16
  sentimantic:
    image: lorenzoranucci/sentimantic
    build: ./
    depends_on:
      - postgres
      - lookup
    container_name: sentimantic
    tty: true
    volumes: 
      - ./:/home/Sentimantic
    restart: always
  lb:
    image: dockercloud/haproxy
    links:
      - lookup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 1111:80
    restart: always
    
