version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: sentimantic
      POSTGRES_USER: sentimantic
      PGDATA: /var/lib/postgresql/data/sentimantic
    ports:
      - 54320:5432
    volumes:
      - ./.database:/var/lib/postgresql/data/sentimantic
    networks:
      - database
  lookup:
    image: dbpedia/lookup
    command: java -jar /opt/lookup/dbpedia-lookup-3.1-jar-with-dependencies.jar /opt/lookup/2015-10/
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 20s
      restart_policy:
        condition: on-failure
    networks:
      - hostnet
      - lookup
    ports:
      - "1111:1111"
  py2Env:
    image: lorenzoranucci/sentimantic
    build: ./
    depends_on:
      - postgres
      - lookup
    tty: true
    volumes:
      - ./:/home/Sentimantic
    networks:
      - database
      - lookup
  brat:
    image: cassj/brat
    volumes:
      - ./snorkel/snorkel/contrib/brat/brat-v1.3_Crunchy_Frog/data:/bratdata
      - ./snorkel/snorkel/contrib/brat/brat-v1.3_Crunchy_Frog/configurations:/bratcfg
    environment:
      BRAT_PASSWORD: brat
      BRAT_USERNAME: brat
      BRAT_EMAIL: lorenzofranco.ranucci@gmail.com
    ports:
      - "8001:80"

networks:
  lookup:
  database:
  hostnet:
      external:
        name: host