version: "2"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sentimantic
      POSTGRES_USER: sentimantic
      PGDATA: /var/lib/postgresql/data/sentimantic
    ports:
      - 54320:5432
    volumes:
      - ./.database:/var/lib/postgresql/data/sentimantic
  lookup:
    container_name: lookup
    image: dbpedia/lookup
    ports:
     - "1111:1111"
    command: java -jar /opt/lookup/dbpedia-lookup-3.1-jar-with-dependencies.jar /opt/lookup/2015-10/
    restart: always
  sentimantic:
    image: lorenzoranucci/sentimantic
    build: ./
    depends_on:
      - postgres
      - lookup
    container_name: sentimantic
    tty: true
    volumes: 
      - ./:/home/Sentimantic
    restart: always
    
