version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sentimantic
      POSTGRES_USER: sentimantic
      PGDATA: /var/lib/postgresql/data/sentimantic
    ports:
      - 54320:5432
    volumes:
      - ./.database:/var/lib/postgresql/data/sentimantic
    networks:
      - database
  lookup:
    image: dbpedia/lookup
    command: java -jar /opt/lookup/dbpedia-lookup-3.1-jar-with-dependencies.jar /opt/lookup/2015-10/
    restart: always
    deploy:
      replicas: 32
      restart_policy:
        condition: on-failure
    networks:
      - lookup
    ports:
      - "1111:1111"
  py2Env:
    image: lorenzoranucci/sentimantic
    build: ./
    depends_on:
      - postgres
      - lookup
    container_name: py2Env
    tty: true
    volumes: 
      - ./:/home/Sentimantic
    networks:
      - database
      - lookup
    restart: always

networks:
  lookup:
  database: